global:
  scrape_interval: 5s

rule_files:
  - "alert-rules.yml"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'realtime-order-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['44.221.49.46:8080']
